### ISSUE TITLE
Nem egyeznek a fv. nevek

### ISSUE THREAD

**Issue by vizvarizoltan** [gyenattila/Cpp#1]
A [Visszatérési érték problémája](https://github.com/gyenattila/Cpp/blob/master/cpp.md#visszat%C3%A9r%C3%A9si-%C3%A9rt%C3%A9k-probl%C3%A9m%C3%A1ja) alatt a második példa programban az elsőhöz hasonlóan a `concat()` fv. szerepel, azonban az alatta lévő magyarázatban `add()` -ként történik a hivatkozás rá.

**Comment by gyenattila** [comment]
Köszi az észrevételt. Javítva.
